### ISSUE TITLE
Moving just the contents up from directory

### ISSUE THREAD

**Issue by edwardessing** [rbardini/metalsmith-move-up#7]
I was wondering if there is a way that I can move just the contents one (or more) levels up from a directory. 
For example:
`| main folder`
`| – – 1.jpg`
`| – – subfolder`
`| – – | – – 2.jpg`

In this instance I would like to move `2.jpg` into the main folder so it would become:
`| main folder`
`| – – 1.jpg`
`| – – 2.jpg`
`| – – subfolder`

Is this possible? Thanks

**Comment by mcdonnelldean** [comment]
Yes, see the example. You can move multiple directories.
